### ISSUE TITLE
failed to install latest plone in Windows 10

### ISSUE THREAD

**Issue by claymorz** [plone/Installers-UnifiedInstaller#100]
Hi,
I trid to intall Plone-5.2.1-UnifiedInstaller-r2 in my computer following the instruction,but got an error message:
 Preparing python virtualenv
Traceback (most recent call last):
  File "helper_scripts\windows_install.py", line 107, in <module>
    vepackagedir = glob.glob(os.path.join(opt.target, 'virtualenv*'))[0]
IndexError: list index out of range

need your help.

**Comment by tkimnguyen** [comment]
Yeah I’m trying to fix this. Please see https://community.plone.org/t/testing-unified-installer-on-windows-plone-5-2-1-python-2-7/11688/2?u=tkimnguyen

**Comment by tkimnguyen** [comment]
In the meantime maybe try the Docker instead. https://community.plone.org/t/running-plone-docker-image-on-windows/11586?u=tkimnguyen

**Comment by claymorz** [comment]
ok,i will try that,thanks.

**Comment by jensens** [comment]
This works now again (5.2.4) with some limitations (see docs/windows.rst).
