### ISSUE TITLE
Installer for 5.2.4

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/Installers-UnifiedInstaller#112]
Can we have an installer for 5.2.4?
Probably PR #110 needs to be merged first, if that is deemed good enough.
Some links:

- Versions: https://dist.plone.org/release/5.2.4/versions.cfg
- pip constraints: https://dist.plone.org/release/5.2.4/constraints.txt
- Launchpad: https://launchpad.net/plone/5.2/5.2.4
- Release page on plone.org, private for the moment: https://plone.org/download/releases/5.2.4

**Comment by jensens** [comment]
Done: https://github.com/plone/Installers-UnifiedInstaller/actions/runs/620748177
The Artifact needs upload to the official locations.

**Comment by jensens** [comment]
Artifact is https://github.com/plone/Installers-UnifiedInstaller/suites/2177111255/artifacts/44780402

**Comment by jensens** [comment]
Another one: The Artifact contains both, the ZIP and the tgz. so do not upload the artifact but the two single builds inside. zip is way easier on Windows., so we need both.

@mauritsvanrees Please close the issue once uploaded.

**Comment by mauritsvanrees** [comment]
Thank you!

I have uploaded both to https://launchpad.net/plone/5.2/5.2.4
If we want a different short description, we can change it. For the tarball I copied the description from 5.2.2:

> Unified Installer tarball -- builds Plone on most Linux/macOS/Windows 10 systems

For the zip file I made it:

> Unified Installer zip -- same as tarball, but easier to extract on Windows
