### ISSUE TITLE
Error: Couldn't find a distribution for 'plone.recipe.precompiler'

### ISSUE THREAD

**Issue by me-kell** [plone/Installers-UnifiedInstaller#24]
I get the following error when installing with `Plone-4.3.4-UnifiedInstaller.tgz`:

```
Couldn't find index page for 'plone.recipe.precompiler' (maybe misspelled?)
Getting distribution for 'plone.recipe.precompiler'.
While:
  Installing.
  Getting section precompiler.
  Initializing section precompiler.
  Installing recipe plone.recipe.precompiler.
  Getting distribution for 'plone.recipe.precompiler'.
Error: Couldn't find a distribution for 'plone.recipe.precompiler'.
```

My install command params are the following:

```
./install.sh --clients=2 --target=/home/Plone-4.3.4 --instance=zeocluster --daemon-user=plone_daemon --owner=plone_buildout --group=plone_group --clients=2 --password=admin --libjpeg=yes --readline=no --build-python zeo
```

if running the buildout (after getting the error above), the buildout gets `plone.recipe.precompiler` and Plone-4.3.4 seems to work. Some hint?

**Comment by me-kell** [comment]
I get this error also when installing with `Plone-5.0b2-UnifiedInstaller.tgz`:

    Couldn't find index page for 'plone.recipe.precompiler' (maybe misspelled?)
    While:
      Installing.
      Getting section precompiler.
      Initializing section precompiler.
      Installing recipe plone.recipe.precompiler.
      Getting distribution for 'plone.recipe.precompiler==0.6'.
    Error: Couldn't find a distribution for 'plone.recipe.precompiler==0.6'.

**Comment by smcmahon** [comment]
When you have the same problem with a new installer version please open a new ticket -- or at least make sure you reopen the issue. Otherwise, you've added a note to a closed issue, and there's a good chance it won't be seen.

This is fixed in installer version r1, already uploaded to https://launchpad.net/plone/5.0/5.0b2/+download/Plone-5.0b2-UnifiedInstaller-r1.tgz

**Comment by me-kell** [comment]
Thank you! You're right. After commenting the issue I realized that I cannot reopen the issue (maybe insufficient rights).

I can confirm that the UnifiedInstallerInstaller-r1 works as expected under debian-7.8.0-amd64.
