### ISSUE TITLE
Move to bobtemplates.plone?

### ISSUE THREAD

**Issue by gforcada** [plone/Installers-UnifiedInstaller#26]
Seeing #25, is there any plan about moving to bobtemplates.plone? Now that seems we are using it as the default way to create add-ons the next step for adoption would be to use it on the unified installer.

Has that been considered for Plone 5.x? (maybe for 5.0 we want to be conservative)

**Comment by smcmahon** [comment]
Yes, this is the plan for 5. It seems to me that a major version change is a good opportunity for this kind of change as nobody expects everything to be the same.

The zopeskel problems have also multiplied with all the setuptools chaos. paster isn't really being maintained.

**Comment by smcmahon** [comment]
Done with 5
