### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by svx** [plone/Installers-UnifiedInstaller#27]
- change links from developer.plone.org to docs.plone.org
- rewrite readme, according to best practice [already wip in branch: https://github.com/plone/Installers-UnifiedInstaller/tree/docs_overhaul]
- mention also homebrew not only mac ports
- change links from dev.plone.org github issue tracker
- update contact to community ?

**Comment by smcmahon** [comment]
The links have been generally updated.

**Comment by svx** [comment]
- [ ] make different OS's more clear
- [ ] add note about OSX and groups/user

**Comment by svx** [comment]
@smcmahon do we have to link the README.txt to README.rst ? 

I would like to use some nice rst syntax thingies to have a awesome rendered README.rst which is confirm with our best practices and just gives user a nice look and feel.

But this is certainly not possible with our current setup.

Would it be possible to split the readme's ? I know that would mean a bit more work, but IMHO in the long run it would give us some advantages.

**Comment by svx** [comment]
Include docs here: http://docs.plone.org/manage/installing/installation.html#installing-plone-using-the-unified-unix-installer

**Comment by smcmahon** [comment]
+1 for all of that. Linking README.txt and README.rst seemed like a good idea at the time, but isn't really useful.

As for splitting, the current document is ludicrously long. A remnant from an era when people read long things.

Go for it!

**Comment by svx** [comment]
@smcmahon would you like to review https://github.com/plone/Installers-UnifiedInstaller/tree/docs_overhaul ?

**Comment by smcmahon** [comment]
This is a big improvement! Merge it or create a pull request, and we'll work from there.

Thanks!
