### ISSUE TITLE
add a short description how to get a working "Plone-x.x.x-UnifiedInstaller.tgz" from a clone of this repository

### ISSUE THREAD

**Issue by me-kell** [plone/Installers-UnifiedInstaller#29]
please add a short description how to get a working "Plone-x.x.x-UnifiedInstaller.tgz" from a clone of this repository: preparing output directories, etc., adding "packages" directory and files, running "buildme.sh", etc.

**Comment by smcmahon** [comment]
Done. See UPDATING_ME.txt.

**Comment by me-kell** [comment]
What are the requirements for get a working "Plone-x.x.x-UnifiedInstaller.tgz" from a clone of this repository? I've followed the instructions in UPDATING_ME.txt without success. I probably missed some point. Here my steps:

with a debian "minimal installation" prepared for plone installation with

    apt-get install -y \
        gcc g++ make tar patch gzip bzip2 bash curl wget \
        build-essential libssl-dev zlib1g-dev libjpeg8-dev libreadline-dev \
        libxml2-dev libxslt1-dev \
        wv poppler-utils \
        sudo git`

clone repository

    cd ~
    git clone https://github.com/plone/Installers-UnifiedInstaller.git

following the instructions on `UPDATING_ME.txt`

    cd ~/Installers-UnifiedInstaller/base_skeleton
    rm *versions.cfg
    ../fetch_versions.py

    ../install.sh zeo

I get the message

    The install script directory must contain
    packages and helper_scripts subdirectories.

and 

    ../update_packages.py
    Traceback (most recent call last):
      File "../update_packages.py", line 31, in <module>
        import pkg_resources
    ImportError: No module named pkg_resources

What do I miss?

**Comment by smcmahon** [comment]
If you are working from a git clone you will not have the binary packaages. For a good starting point, copy the "packages" subdirectory from a previous installer tarball.

(That's been added to the UPDATING_ME doc.)
