### ISSUE TITLE
OS X Unified Installer pyexpat Error

### ISSUE THREAD

**Issue by josadeluca** [plone/Installers-UnifiedInstaller#31]
Mac OS X 10.10.3 (Yosemite)
Plone 4.3.5
The command I'm running is:
./install.sh zeo --target=/Users/jad52/MySites/testsite --build-python

Installer fails with the following message in the console:
Failed: Python must include xml.parsers.expat module.

A snippet from the log file shows this:
Python build finished, but the necessary bits to build these modules were not found:
bsddb185           dl                 gdbm            
imageop            linuxaudiodev      ossaudiodev     
spwd               sunaudiodev                        
To find the necessary bits, look in setup.py in detect_modules() for the module's name.

Failed to build these modules:
_elementtree       pyexpat                            

running build_scripts
running install_lib

**Comment by smcmahon** [comment]
I was unable to reproduce this with the 4.3.6 installer on 10.10.4 with XCode.

The inability to build a Python component generally means that a system development library was missing. You might try reinstalling XCode's command line tools.

The installer should work with Apple's Python (so long as you have the development tools and libraries included with XCode), so there should not be a need to build a new Python.
