### ISSUE TITLE
5.0b2 Unified Installer fails on OSX 10.10.3 with User/Group definitions

### ISSUE THREAD

**Issue by pfraterdeus** [plone/Installers-UnifiedInstaller#32]
As noted here : http://article.gmane.org/gmane.comp.web.zope.plone.user/124713
See below for UPDATE...

-----
After receiving the User/Group error shown below, I manually added the plone,
plone_buildout, and plone_daemon users and eponymous groups through the OS X
Users & Groups System Prefs panel (in fact, they were already there, so I
deleted and re-added). However, the same thing occurs regardless.

I'm not sure about the code, but doing some searching on the error brings up
"UNKNOWN_USER_ENV" and the code which raises this seems to simply give up
without even testing for the existence of the correct user and group, if it's
not under either linux or BSD.

https://github.com/plone/Installers-UnifiedInstaller/blob/master/helper_scripts/
user_group_utilities.sh

I have XCode and Command Line Tools installed

~/Downloads/Plone-5.0b2-UnifiedInstaller-r1  <at>  nealta-geala (peterf) | =>
xcode-select --install xcode-select: error: command line tools are already
installed, use "Software Update" to install updates
________________________________________________________________________________
| ~/Downloads/Plone-5.0b2-UnifiedInstaller-r1  <at>  nealta-geala (peterf) | => gcc
--version Configured with:
--prefix=/Applications/Xcode.app/Contents/Developer/usr
--with-gxx-include-dir=/usr/include/c++/4.2.1 Apple LLVM version 6.1.0
(clang-602.0.53) (based on LLVM 3.6.0svn) Target: x86_64-apple-darwin14.3.0
Thread model: posix

The Installation Error here: | ~/Downloads/Plone-5.0b2-UnifiedInstaller-r1  <at> 
nealta-geala (peterf) | => sudo ./install.sh zeo

Testing /usr/bin/python2.7 for Zope/Plone requirements.... /usr/bin/python2.7
looks OK. We will use it.

Root install method chosen. Will install for use by users: ZEO & Client Daemons:
     plone_daemon Code Resources & buildout: plone_buildout

Detailed installation log being written to
/Users/peterf/Downloads/Plone-5.0b2-UnifiedInstaller-r1/install.log Installing
Plone 5.0b2 at /Applications/Plone

We do not know how to add users and groups in this environment. Please add users
and group manually, then try again. See README.txt for instructions on how to
proceed.

----

UPDATE:

Hmm. Of course, having written the above, I now find that indeed the version in 
4.3.3 does support dscl under OSX... 
/Applications/Plone-4.3.3-UnifiedInstaller/helper_scripts/user_group_utilities.sh

So, maybe it just got lost in the 5.0 beta?
I'll patch it from the 4.3.3 into my 5.0b installer 
../helper_scripts/user_group_utilities.sh

----
copying the 4.3.3 file into the 5.0b helper_scripts/  solved the immediate User/Group concern, although there are still issues. In particular, if one reruns the install.sh (which I've been doing repeatedly, due to libjpeg problems - another issue) the script again complains about the User/Group configs it finds or doesn't find. However, if one then immediately reruns install.sh AGAIN, it proceeds to set up the user/group as it likes. 

so:
Testing /usr/bin/python2.7 for Zope/Plone requirements....
/usr/bin/python2.7 looks OK. We will use it.

Root install method chosen. Will install for use by users:
  ZEO & Client Daemons:      plone_daemon
  Code Resources & buildout: plone_buildout

Detailed installation log being written to /Users/peterf/Downloads/Plone-5.0b2-UnifiedInstaller-r1/install.log
Installing Plone 5.0b2 at /Applications/Plone

Using dscl to create users and groups
Using dscl (Directory Service command line utility) to create group 
plone_group with gid 57 in directory /Local/Default ...
Creating user ...
Using dscl (Directory Service command line utility) to create user 
plone_daemon with uid 52 in directory /Local/Default ...
id for plone_daemon returned
uid=52(plone_daemon) gid=57 groups=57,12(everyone),61(localaccounts),403(com.apple.sharepoint.group.2),100(_lpoperator),402(com.apple.sharepoint.group.1)
Expected to find uid for plone_daemon and gid for plone_group but did not.
Please use your system tools to create/edit users and groups, then try again.

________________________________________________________________________________
| ~/Downloads/Plone-5.0b2-UnifiedInstaller-r1 @ nealta-geala (peterf) 
| => sudo rm -r  /Applications/Plone/zeocluster
________________________________________________________________________________
| ~/Downloads/Plone-5.0b2-UnifiedInstaller-r1 @ nealta-geala (peterf) 
| => sudo ./install.sh zeo

Testing /usr/bin/python2.7 for Zope/Plone requirements....
/usr/bin/python2.7 looks OK. We will use it.

Root install method chosen. Will install for use by users:
  ZEO & Client Daemons:      plone_daemon
  Code Resources & buildout: plone_buildout

Detailed installation log being written to /Users/peterf/Downloads/Plone-5.0b2-UnifiedInstaller-r1/install.log
Installing Plone 5.0b2 at /Applications/Plone

Using dscl to create users and groups
Using dscl (Directory Service command line utility) to create group 
plone_group with gid 63 in directory /Local/Default ...
Creating user ...
Using dscl (Directory Service command line utility) to create user 
plone_daemon with uid 50 in directory /Local/Default ...
Creating plone_daemon user ...
Using dscl (Directory Service command line utility) to create user 
plone_buildout with uid 52 in directory /Local/Default ...

**Comment by smcmahon** [comment]
Workaround: remove the "exit 1" in the unknown platform check_ug_ability routine in helper_scripts/users_group_utilities.sh

**Comment by pfraterdeus** [comment]
Thanks Steve! 
As noted, v4.3.3 helper_scripts/users_group_utilities.sh also includes the code which correctly adds the user/groups under OS X, whereas the 5.0b2 omits this.

**Comment by smcmahon** [comment]
We've been stripping out OS X-specific code in the installer, and the Apple directory services code that adds users and groups on OS X was one of the victims. That code was complex, and didn't work on OS X servers connected to LDAP. It seemed like a better idea to let OS X sysadmin's handle this with Apple's own utilities.

**Comment by pfraterdeus** [comment]
Ah, got ya. Good enough ;-)
