### ISSUE TITLE
ImportError: No module named dexterity.localcommands.dexterity

### ISSUE THREAD

**Issue by sif77** [plone/Installers-UnifiedInstaller#33]
Tried zopeskel.dexterity-1.5.4.1 with Plone 4.3.4 and 4.3.6 :

[example.conference]$ ../../bin/paster addcontent -l
Warning: could not load entry point dexterity_behavior (ImportError: No module named dexterity.localcommands.dexterity)
Warning: could not load entry point dexterity_content (ImportError: No module named dexterity.localcommands.dexterity)
Available templates:
browserlayer: A Plone browserlayer
form: A form skeleton
formfield: Schema field for a form
i18nlocale: An i18n locale directory structure
portlet: A Plone 3 portlet
view: A browser view skeleton
zcmlmeta: A ZCML meta directive skeleton

Thanks for your help

**Comment by djowett** [comment]
Hi,
    I've had fights like this in the past with zopeskel / paster.

Nowadays though I avoid it.... choosing to use:

- [mrbob](http://mrbob.readthedocs.org/) for templating eggs
- creating dexterity either through the web[see plone 
training](http://plone-training.readthedocs.org/en/latest/dexterity.html)
   OR directly in code without templating - as there's a lot less 
boilerplate code in dexterity cf archetypes

Hope this helps!




On 12/06/15 14:12, sif77 wrote:
>
> Tried zopeskel.dexterity-1.5.4.1 with Plone 4.3.4 and 4.3.6 :
>
> [example.conference]$ ../../bin/paster addcontent -l
> Warning: could not load entry point dexterity_behavior (ImportError: 
> No module named dexterity.localcommands.dexterity)
> Warning: could not load entry point dexterity_content (ImportError: No 
> module named dexterity.localcommands.dexterity)
> Available templates:
> browserlayer: A Plone browserlayer
> form: A form skeleton
> formfield: Schema field for a form
> i18nlocale: An i18n locale directory structure
> portlet: A Plone 3 portlet
> view: A browser view skeleton
> zcmlmeta: A ZCML meta directive skeleton
>
> Thanks for your help
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/plone/Installers-UnifiedInstaller/issues/33>.
>

-- 
Daniel Jowett

*Jowett Enterprises Ltd*
Tel: 0333 3 553 773
Mobile: 07870 667 126
daniel@jowettenterprises.com
www.jowettenterprises.com

**Comment by smcmahon** [comment]
It is getting increasingly hard to keep zopeskel working with new versions of setuptools. I'll take a shot and see if I can get it going again.

**Comment by smcmahon** [comment]
The general setuptools compatibility problem is fixed for the P5 installer.

**Comment by sif77** [comment]
Sorry, what is the P5 installer ?

Thank you

**Comment by svx** [comment]
@sif77 That is the Unified Installer for Plone 5 [beta]

**Comment by encolpe** [comment]
@smcmahon Have you a link to the commit to let us fix our not so old Plone 4.3 installers ?

**Comment by sif77** [comment]
https://pypi.python.org/packages/source/z/zopeskel.dexterity/zopeskel.dexterity-1.5.4.1.zip
https://pypi.python.org/packages/source/s/setuptools/setuptools-7.0.tar.gz

Thank you

**Comment by encolpe** [comment]
I found a workaround. In your egg created with the dexterity zopeskel template you have a bootstrap.py file and a buildout.cfg file.b

1. Go in the egg folder
2. In the buildout.cfg file add ```ZopeSkel=2.21.2``` in the [versions] section
3. Launch ```../../../Python-2.7/bin/python bootstrap.py -v 2.2.5 -c buildout.cfg```
4. Then you can use ```bin/paster addcontent -l```

Regards

**Comment by rfleschenberg** [comment]
Can I work around this on Plone 4 by installing a compatible version of setuptools? If yes, which version?

**Comment by rfleschenberg** [comment]
IIUC, this bug means that the documentation at http://docs.plone.org/4/en/external/plone.app.dexterity/docs/prerequisite.html is effectively invalid.
