### ISSUE TITLE
Why the version of zc.buildout in Plone 4.3 branch is 2.2.5?

### ISSUE THREAD

**Issue by idgserpro** [plone/Installers-UnifiedInstaller#40]
Why the version of zc.buildout in Plone 4.3 branch is [2.2.5](https://github.com/plone/Installers-UnifiedInstaller/blob/4.3-maintenance/buildout_templates/buildout.cfg#L203), if the Plone 4.3 is tested with zc.buildout [1.7.1](http://jenkins.plone.org/job/plone-4.3-python-2.7/ws/bin/jenkins-test/*view*/)?

**Comment by smcmahon** [comment]
The version chosen for the installer is meant to work with the components included with it. Those are not necessarily the same as the coredev buildout.

If you are encountering an error or have a suggestion, file a specific issue report.
