### ISSUE TITLE
Unified Installer for plone 4 Not working

### ISSUE THREAD

**Issue by prakharjoshi** [plone/Installers-UnifiedInstaller#48]
I am trying to create an instance using Plone 4 unified installer and I did the bootstrapping using ``python bootstrap.py`` under the virtual environment. 

Now when I am trying to run the buildout using ``bin/buildout`` it is showing an error. Here is the error 

```
While:
  Installing.
  Getting section instance.
  Initializing section instance.
  Installing recipe plone.recipe.zope2instance.

An internal error occurred due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "/home/prakhar/PP/buildout-cache/eggs/zc.buildout-2.4.5-py2.7.egg/zc/buildout/buildout.py", line 1992, in main
    getattr(buildout, command)(args)
  File "/home/prakhar/PP/buildout-cache/eggs/zc.buildout-2.4.5-py2.7.egg/zc/buildout/buildout.py", line 550, in install
    [self[part]['recipe'] for part in install_parts]
  File "/home/prakhar/PP/buildout-cache/eggs/zc.buildout-2.4.5-py2.7.egg/zc/buildout/buildout.py", line 1135, in __getitem__
    options._initialize()
  File "/home/prakhar/PP/buildout-cache/eggs/zc.buildout-2.4.5-py2.7.egg/zc/buildout/buildout.py", line 1239, in _initialize
    self.initialize()
  File "/home/prakhar/PP/buildout-cache/eggs/zc.buildout-2.4.5-py2.7.egg/zc/buildout/buildout.py", line 1245, in initialize
    recipe_class = _install_and_load(reqs, 'zc.buildout', entry, buildout)
  File "/home/prakhar/PP/buildout-cache/eggs/zc.buildout-2.4.5-py2.7.egg/zc/buildout/buildout.py", line 1199, in _install_and_load
    allow_hosts=buildout._allow_hosts
  File "/home/prakhar/PP/buildout-cache/eggs/zc.buildout-2.4.5-py2.7.egg/zc/buildout/easy_install.py", line 849, in install
    return installer.install(specs, working_set)
  File "/home/prakhar/PP/buildout-cache/eggs/zc.buildout-2.4.5-py2.7.egg/zc/buildout/easy_install.py", line 636, in install
    for_buildout_run=for_buildout_run):
TypeError: get_dist() got an unexpected keyword argument 'for_buildout_run'
*************** PICKED VERSIONS ****************
[versions]

*************** /PICKED VERSIONS ***************
 ```

**Comment by gforcada** [comment]
*I fixed your formatting, add triple backticks to make some text preformatted*

**Comment by smcmahon** [comment]
What version of the installer were you using?

Why did you need to bootstrap? The buildout directories created by the installer should be ready to run "bin/buildout".

**Comment by prakharjoshi** [comment]
I am using unified installer version 4.3.4

**Comment by prakharjoshi** [comment]
@gforcada Sorry but I haven't seen any changes yet. Can you tell me where I am doing wrong ?

**Comment by cewing** [comment]
@prakharjoshi, if you put triple-backticks ( \`\`\` some text \`\`\`  ) around a piece of formatted text like a stack trace, it makes it appear properly in a github issue.  See the difference between these two:

this is not
  formatted text
but it really should
  be

```
this is not
  formatted text
but it really should
  be
```

**Comment by prakharjoshi** [comment]
@cewing  Oh yeah Thanks :)

**Comment by prakharjoshi** [comment]
@smcmahon I am trying to create an instance using unified installer 4.3.6 and I guess there we need to do the bootstrapping before running buildout, right ?

**Comment by svx** [comment]
@prakharjoshi no you do not need that, as it is written in the docs:

```
# Extract the downloaded file
#
tar -xf Plone-5.0-UnifiedInstaller.tgz
#
# Go the folder containing installer script
#
cd Plone-5.0-UnifiedInstaller
#
# Run script
./install.sh
```
If you use the installer with certain options like set a password and a install path, please run:

```
./install.sh --help
```

you can find more info here:

http://docs.plone.org/manage/installing/installation.html

and here:

https://github.com/plone/Installers-UnifiedInstaller/blob/master/docs/index.rst

**Comment by prakharjoshi** [comment]
@svx  Yeah that is okay with plone 5 but what if I have to craete a plone 4 instance ?

**Comment by prakharjoshi** [comment]
Okay I got it :)

**Comment by svx** [comment]
@prakharjoshi the same goes for the Plone 4, the only difference is that the UI-installer for Plone 4 comes without the GUI, so will need to run ./install.sh standalone for example

**Comment by smcmahon** [comment]
The Unified Installer (sort of) bootstraps the buildout. So there's no need
to bootstrap it unless you're changing your Python.
