### ISSUE TITLE
unknown warning option '-Werror=unused-command-line-argument-hard-error-in-future'

### ISSUE THREAD

**Issue by tkimnguyen** [plone/Installers-UnifiedInstaller#50]
The 5.0.2 unified installer gets lots of these warnings on OS X 10.11.3:

```
warning: unknown warning option '-Werror=unused-command-line-argument-hard-error-in-future'; did you mean '-Werror=unused-command-line-argument'? [-Wunknown-warning-option]
```

**Comment by smcmahon** [comment]
Yes, Apple is notifying us that they're in the process of making sure their compiler won't be interoperable with the GNU compiler. Ironically, it's the Apple-built Python that's supplying the compile flags that they're complaining about. Presumably, Apple will fix one or the other at some future time.

**Comment by tkimnguyen** [comment]
thx Steve!
