### ISSUE TITLE
Remove SSLv2 requirement

### ISSUE THREAD

**Issue by fulv** [plone/Installers-UnifiedInstaller#52]
SSLv2 has fallen into disgrace, so perhaps we should no longer check for its presence.

Moreover, if you try to build openssl from source, the latest release of the LTS version (1.0.2g) has v2 disabled by default and makes it really hard to enable.  At least, I wasn't able to without some ugly hacks in .c and .h files.

https://www.openssl.org/source/

**Comment by smcmahon** [comment]
I'll check this out. We definitely shouldn't be looking for v2. In fact, back when we were using earlier versions of Python, we used to patch it on build to make sure it didn't require v2.

**Comment by smcmahon** [comment]
The Unified Installer does not check for SSLv2. It only checks to see if the openssl/ssl.h header file is findable via the standard autoconf mechanisms.

**Comment by smcmahon** [comment]
Close was premature.

**Comment by smcmahon** [comment]
OK, there is an SSLv2 check, but it doesn't do anything. It's leftover from an earlier version which had some code to disable ssl v2 for an earlier version of Python.

**Comment by fulv** [comment]
Why is there a `have_ssl2` in the results, then?

```
have_ssl2='no'
have_ssl='no'
have_ssl_h='yes'
```

See https://gist.github.com/fulv/ec0e32780c5e3ff1c7bc5193cb56751c

**Comment by smcmahon** [comment]
There is a check, but the installer doesn't make any decisions based on the result.
