### ISSUE TITLE
Error installing Plone-5.1rc1 on Debian 9

### ISSUE THREAD

**Issue by paskyorg** [plone/Installers-UnifiedInstaller#63]
> root@debian9-32:~/Plone-5.1rc1-UnifiedInstaller#
> 
>  ./install.sh --clients=2 zeo
> 
> Testing /usr/bin/python2.7 for Zope/Plone requirements....
> /usr/bin/python2.7 looks OK. We will use it.
> 
> /usr/bin/python2.7
> 
> Root install method chosen. Will install for use by users:
>   ZEO & Client Daemons:      plone_daemon
>   Code Resources & buildout: plone_buildout
> 
> 
> Detailed installation log being written to /root/Plone-5.1rc1-UnifiedInstaller/install.log
> Installing Plone 5.0.9 at /opt/plone
> 
> helper_scripts/main_install_script.sh: línea 723: helper_scripts/user_group_utilities.sh: No existe el fichero o el directorio
> helper_scripts/main_install_script.sh: línea 726: check_ug_ability: no se encontró la orden
> helper_scripts/main_install_script.sh: línea 728: create_group: no se encontró la orden
> helper_scripts/main_install_script.sh: línea 729: create_user: no se encontró la orden
> helper_scripts/main_install_script.sh: línea 730: check_user: no se encontró la orden
> helper_scripts/main_install_script.sh: línea 731: create_user: no se encontró la orden
> helper_scripts/main_install_script.sh: línea 732: check_user: no se encontró la orden
> chown: usuario inválido: «plone_buildout:plone_group»
> Creating Python virtual environment.
> New python executable in /opt/plone/zeocluster/bin/python2.7
> Also creating executable in /opt/plone/zeocluster/bin/python
> Installing setuptools, pip, wheel...done.
> chown: usuario inválido: «plone_buildout:plone_group»
> Installing zc.buildout in virtual environment.
> Unpacking buildout cache to /opt/plone/buildout-cache
> chown: usuario inválido: «plone_buildout:plone_group»
> Copying Plone-docs
> chown: usuario inválido: «plone_buildout:plone_group»
> chown: usuario inválido: «plone_buildout:plone_group»
> Buildout failed. Unable to continue
> 
> Installation has failed.
> See the detailed installation log at /root/Plone-5.1rc1-UnifiedInstaller/install.log
> to determine the cause.

The content of install.log file is:

> Detailed installation log
> Starting at mié oct 25 16:01:42 CEST 2017
> Processing ./packages/zc.buildout-2.9.4.tar.gz
> Requirement already satisfied: setuptools>=8.0 in /opt/plone/zeocluster/lib/python2.7/site-packages (from zc.buildout==2.9.4)
> Building wheels for collected packages: zc.buildout
>   Running setup.py bdist_wheel for zc.buildout: started
>   Running setup.py bdist_wheel for zc.buildout: finished with status 'done'
>   Stored in directory: /root/.cache/pip/wheels/20/e0/f6/814537b9ae4df7ea0aa00e368bc5430acf72ceeb56949d3fd2
> Successfully built zc.buildout
> Installing collected packages: zc.buildout
> Successfully installed zc.buildout-2.9.4
> sudo: unknown user: plone_buildout
> sudo: no se puede inicializar la política de plugin

The helper scripts not working.

**Comment by smcmahon** [comment]
Unable to reproduce on later installers.
