### ISSUE TITLE
I get the following error when installing with Plone-5.1rc1-UnifiedInstaller.tgz:

### ISSUE THREAD

**Issue by bobwassell** [plone/Installers-UnifiedInstaller#64]
Couldnt find index page for plone.recipe.precompiler (maybe misspelled?)
While:
  Installing.
  Getting section precompiler.
  Initializing section precompiler.
  Installing recipe plone.recipe.precompiler.
  Getting distribution for plone.recipe.precompiler.
Error: Couldnt: command not found

Opening up a ticket for this version, let me know if i shouldn't have done this.

**Comment by smcmahon** [comment]
Resolved with later installers.
