### ISSUE TITLE
5.1-rc2: Error: Couldn't find a distribution for 'plone.recipe.precompiler'.

### ISSUE THREAD

**Issue by glimmung** [plone/Installers-UnifiedInstaller#65]
I see that others have reported this in previous builds, but am opening a new issue as I am getting this on 5/1-rc2, which I do not see reported: -

Not found: /opt/Plone-5.1-rc2/buildout-cache/downloads/dist/plone.recipe.precompiler/
Not found: /opt/Plone-5.1-rc2/buildout-cache/downloads/dist/plone.recipe.precompiler/
Couldn't find index page for 'plone.recipe.precompiler' (maybe misspelled?)
Getting distribution for 'plone.recipe.precompiler'.
Not found: /opt/Plone-5.1-rc2/buildout-cache/downloads/dist/plone.recipe.precompiler/
Not found: /opt/Plone-5.1-rc2/buildout-cache/downloads/dist/plone.recipe.precompiler/
Couldn't find index page for 'plone.recipe.precompiler' (maybe misspelled?)
While:
  Installing.
  Getting section precompiler.
  Initializing section precompiler.
  Installing recipe plone.recipe.precompiler.
  Getting distribution for 'plone.recipe.precompiler'.
Error: Couldn't find a distribution for 'plone.recipe.precompiler'.

**Comment by deankarlen** [comment]
Workaround: unwrap buildout-cache.tar.bz2 from the packages area and add missing files:

- bzip2 -d buildout-cache.tar.bz2
- tar -xf buildout-cache.tar

Copy current versions of the 2 missing .zip files from:
https://pypi.python.org/pypi/plone.recipe.precompiler/0.6
https://pypi.python.org/pypi/plone.recipe.command
into: buildout-cache/downloads/dist
and repackage the file:

- tar -cf buildout-cache.tar buildout-cache
- bzip2 buildout-cache.tar

**Comment by smcmahon** [comment]
Fixed with a later release. Sorry for failing to close in a timely way.
