### ISSUE TITLE
5.0.8-r1 - Error: Wheels are not supported

### ISSUE THREAD

**Issue by glimmung** [plone/Installers-UnifiedInstaller#66]
In 5.0.08-r1 the installer runs, but any attempt to install further product fails with e.g.: -

Using unpack_wheel() shim over the deprecated wheel_to_egg() hook.
Please update your wheel extension implementation for one that installs a .whl
handler in zc.buildout.easy_install.UNPACKERS
While:
  Installing client1.
  Getting distribution for 'collective.themesitesetup'.
Error: Wheels are not supported

....which seems to be am issue with the version of buildout in the installer.

**Comment by glimmung** [comment]
Workaround: -

[buildout]
extensions = buildout.wheel

(via Plone Community board)

**Comment by smcmahon** [comment]
This was fixed in the 5.1 series. glimmung's workaround is good for earlier releases.
