### ISSUE TITLE
Adjusting tag.gz content

### ISSUE THREAD

**Issue by svx** [plone/Installers-UnifiedInstaller#70]
Hi,

Would it an idea to adjust the content of the UI tar.gz we offer on Launchpad ?

Or should we split them into a ``production`` aka you use on your server and a ``all included`` one.

Do not get picky on the names for now :)

It is just the currently we have lots of stuff in the UI.tar.gz what is not needed on `` prod`` and even make it potentially less perfect to have these files lying around on ``prod`` machines.

These are of course are super cool and awesome if you use the UI on your desktop but these are less cool on ``prod`` machines where the included files should be only the minimal needed without any *not for prod needed cruft* :) 

Besides that less content means also faster downloads and more :)

**Comment by smcmahon** [comment]
The 5.2.0+ version of the installer has pretty much eliminated all the extra packages.
