### ISSUE TITLE
GettingcError: Couldn't find a distribution for 'plone.recipe.precompiler'.

### ISSUE THREAD

**Issue by naveedd** [plone/Installers-UnifiedInstaller#77]
Getting the following error while installing latest version on centos7 

Got zodbpickle 0.7.0.
Not found: /opt/plone1/buildout-cache/downloads/dist/plone.recipe.precompiler/
Not found: /opt/plone1/buildout-cache/downloads/dist/plone.recipe.precompiler/
Couldn't find index page for 'plone.recipe.precompiler' (maybe misspelled?)
Getting distribution for 'plone.recipe.precompiler'.
Not found: /opt/plone1/buildout-cache/downloads/dist/plone.recipe.precompiler/
Not found: /opt/plone1/buildout-cache/downloads/dist/plone.recipe.precompiler/
Couldn't find index page for 'plone.recipe.precompiler' (maybe misspelled?)
While:
  Installing.
  Getting section precompiler.
  Initializing section precompiler.
  Installing recipe plone.recipe.precompiler.
  Getting distribution for 'plone.recipe.precompiler'.
Error: Couldn't find a distribution for 'plone.recipe.precompiler'.

**Comment by smcmahon** [comment]
Resolved with later installers.
