### ISSUE TITLE
Unable to install Plone 5.2.0 on Windows 10

### ISSUE THREAD

**Issue by smcmahon** [plone/Installers-UnifiedInstaller#90]
_From community.plone.org_

I have tried to install the new stable version of Plone 5.2.0 under Windows 10, in the following situations:
-installation with the options password, instance and target
-installation by default with only password option.
In any case the installation can not succeed.
The process is interrupted with error messages.
I attach you below the example of the second choice: installation by default.
Does anyone have an idea of what I miss?
Thanks in advance.

```
« Microsoft Windows [version 10.0.17763.615]

(c) 2018 Microsoft Corporation. Tous droits réservés.

C:\Users\Purnata>cd \

C:>cd Plone-5.2.0-UnifiedInstaller

C:\Plone-5.2.0-UnifiedInstaller>windows_install.bat standalone --password=Abhra583*

C:\Plone-5.2.0-UnifiedInstaller>python helper_scripts\windows_install.py standalone --password=XXXXXXXXX

Creating target directory \Users\Purnata\Plone

Extracting buildout cache to target

Traceback (most recent call last):

File "helper_scripts\windows_install.py", line 103, in

with tarfile.open(os.path.join(PACKAGES_HOME, 'buildout-cache.tar.bz2')) as tf:

File "C:\Python27\lib\tarfile.py", line 1675, in open

return func(name, "r", fileobj, **kwargs)

File "C:\Python27\lib\tarfile.py", line 1740, in gzopen

fileobj = gzip.GzipFile(name, mode, compresslevel, fileobj)

File "C:\Python27\lib\gzip.py", line 94, in init

fileobj = self.myfileobj = builtin.open(filename, mode or 'rb')

IOError: [Errno 2] No such file or directory: 'C:\Plone-5.2.0-UnifiedInstaller\packages\buildout-cache.tar.bz2'

[C:\Plone-5.2.0-UnifiedInstaller](file:///C:/Plone-5.2.0-UnifiedInstaller)> »
```

**Comment by TecKnowJoe** [comment]
I'm having the same issue.

**Comment by smcmahon** [comment]
You can work around the installer problem by commenting out lines 100-110 in helper_scripts\windows_install.py. However, this will just reveal another problem that isn't installer related. I'm investigating that and will report back.

**Comment by smcmahon** [comment]
For anyone who wants to follow the related install problem: https://github.com/plone/plone.staticresources/issues/35
