### ISSUE TITLE
5.2.0-r2 installer: `packages` subdirectory missing

### ISSUE THREAD

**Issue by dbitouze** [plone/Installers-UnifiedInstaller#95]
The "5.2.0-r2" installer is missing the `packages` subdirectory: when `install.sh` is run, the installation immediately aborts with the error:

> The install script directory must contain
[...]/Installers-UnifiedInstaller-5.2.0-r2/packages and [...]/Installers-UnifiedInstaller-5.2.0-r2/helper_scripts subdirectories.

AFAICS, the message about `helper_scripts` is a false alarm: this subdirectry isn't missing.

**Comment by jensens** [comment]
wontfix - outdated
