### ISSUE TITLE
windows_installer.py not Python 3 ready

### ISSUE THREAD

**Issue by jensens** [plone/Installers-UnifiedInstaller#98]
The file https://github.com/plone/Installers-UnifiedInstaller/blob/master/helper_scripts/windows_install.py contains `print` statements. See report here https://community.plone.org/t/plone-5-2-1-with-python-3-7-5-on-windows-10/11506

**Comment by smcmahon** [comment]
We've a branch in which this is fixed, but there's no good reason to merge it (and no final ability to test it) until the windows plone.staticresources bug  https://github.com/plone/plone.staticresources/issues/35 is fixed.

**Comment by jensens** [comment]
FYI: our intern @nilshofer is working on it

**Comment by mauritsvanrees** [comment]
Is this done now, with the merge of PR #105?

**Comment by jensens** [comment]
In fact this would need more testing. If there are problems popping up, this could get fixed in the phase between Plone release of 5.2.2 and building the installers. Since the bin/instance is Unix only, and Windows `runwsgi.exe` has to be used, at least the documentation/output needs some love.

**Comment by jensens** [comment]
I would propose the Installer Team sets up an GitHub Action testing for Windows testing. Then upcoming errors can get fixed 
The build step can be done on Linux and the artefact is the Installer. 
Then the Installer can be run on Linux, Macos and Windows. If it runs an instance start should be possible. If an HTTP request is possible to 8080 all is fine.

**Comment by jensens** [comment]
fixed
